### ISSUE TITLE
Include package udev which is required for TVButler support

### ISSUE THREAD

**Issue by psychicsword** [linuxserver/docker-plex#119]
When Plex Media server first starts with this image it displays the following warning message:

```
##################################################################
#  NOTE: Your system does not have udev installed. Without udev  #
#        you won't be able to use DVBLogic's TVButler for DVR    #
#        or for LiveTV                                           #
#                                                                #
#        Please install udev and reinstall Plex Media Server to  #
#        to enable TV Butler support in Plex Media Server.       #
#                                                                #
#        To install udev run: sudo apt-get install udev          #
#                                                                #
##################################################################
```

While not everyone needs the TVButler support it looks like it is important enough that plex is throwing a warning and should be included.

**Comment by aptalca** [comment]
udev prevented plex from installing correctly in the image (I can't remember the details)

And since then, not a single person requested support for TV Butler in this image, so we didn't bother. Plex put the notice in there when they added official support for Live TV and needed an additional dependency for TV Butler.
