### ISSUE TITLE
Plex docker image takes some minutes to load due "Change in ownership detected, please be patient while we chown existing files This could take some time"

### ISSUE THREAD

**Issue by mcgyver83** [linuxserver/docker-plex#188]
I'm running plex docker image on a raspberry pi2 with debian.
My config folder is placed on an external usb drive, NTFS partition mounted in fstab.
Each time I start plex container I have this message and takes minutes to load.
How can I avoid this?

In fact, despite of `sudo chown -R myUser:users config` config folder remain owned by root :(

**Comment by j0nnymoe** [comment]
Posting your docker run/compose command will help.

**Comment by mcgyver83** [comment]
Each day at 18pm I run this script to update the image an start the container

`#!/usr/bin/env bash

docker stop plex;
docker rm plex;
docker pull linuxserver/plex:latest;
docker run \
    --name=/plex \
    --env="PLEX_MEDIA_SERVER_INFO_DEVICE=Docker Container (LinuxServer.io)" \
    --env="PUID=1003" \
    --env="PGID=100" \
    --env="VERSION=docker" \
    --network "host" \
    --volume="/home/pi/plex_database:/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases:rw" \
    --volume="/home/pi/local_drive/docker_plex/logs_tmp:/config/Library/Application Support/Plex Media Server/Logs:rw" \
    --volume="/home/pi/local_drive/docker_plex/config:/config:rw" \
    --volume="/home/pi/local_drive/motioneye_storage:/data/motioneye_pics:rw" \
    --volume="/home/pi/local_drive/tinycammon:/data/tinycammon_video:rw" \
    --volume="/home/pi/local_drive/tinycammon:/data/tinycammon_pics:rw" \
    --volume="/home/pi/local_drive/Film/3D:/data/movies/3D:rw" \
    --volume="/home/pi/local_drive/motioneye_storage:/data/motioneye_video:rw" \
    --volume="/home/pi/local_drive/Backup/Foto_Video/Foto/2018-06-09 - Matrimonio:/data/wedding:rw" \
    --volume="/home/pi/local_drive/Film/2D:/data/movies/2D:rw" \
    --volume="/home/pi/local_drive/Backup/Foto_Video:/data/pictures:rw" \
    --volume="/home/pi/local_drive/Serie:/data/tvshows:rw" \
    --volume="/plex_transcode:/transcode:rw" \
    --restart="unless-stopped" \
    --detach=true \
    linuxserver/plex:latest`

**Comment by thelamer** [comment]
We determine what needs to be chowned based off the UID and GID of the folder. For plex we do a spot check of the library folder so we only chown that when absolutely needed as it takes some time. 

I am afraid you have chosen to use a windows filesystem to host your config files, and because of that you have broken compatibility with the sanity checks we perform which depend on the Linux UID and GID being set for the folders we bind mount into the container. 

We will not be making any logic changes to support this kind of configuration, we will always recommend that especially when it comes to our /config folder it is never mounted on network shares or NTFS/FAT32 drives. (or really any weird FS for that matter)

**Comment by mcgyver83** [comment]
Ok, so I an issue due the fact I'm using NTFS.
I'll check for something readable/writable by windows, linux and osx to replace NTFS.
Thanks
