### ISSUE TITLE
Migration path from plexinc/pms-docker?

### ISSUE THREAD

**Issue by drewcovi** [linuxserver/docker-plex#196]
Is this image generally a direct replacement for plex/pms-docker?

It seems most variables are similar, aside from `PLEX_CLAIM`

**Comment by aptalca** [comment]
yes

**Comment by drewcovi** [comment]
is PLEX_CLAIM a parallel server env to PLEX_TOKEN? or how can we leverage the claim token?

**Comment by aptalca** [comment]
Using the plex claim token requires generating from scratch and/or modifying the plex preferences file. Since we are downstream of plex, we are not comfortable with doing that. We have no control over (or an idea of) when and how plex makes changes to the preferences file as it is closed source.

So no plans of adding that to our image.

We recommend setting up the container with host networking the first time and claim via the web interface (ssh tunnel works if the server is remote). Then you can switch it to bridge networking if you like.
