### ISSUE TITLE
Web interface does not start, s6 errors

### ISSUE THREAD

**Issue by redlegoman** [linuxserver/docker-plex#76]
I create and start exactly as described:
```
docker create \
--name=plex \
--net=host \
-e VERSION=latest \
-e PUID=501 -e PGID=501 \
-e TZ=Europe/London \
-v /data/data1/SHARED/plex1/config \
-v /data/data1/SHARED/plex1/data/tvshows \
-v /data/data1/SHARED/plex1/data/movies \
-v /data/data1/SHARED/plex1/transcode \
linuxserver/plex
```

`docker start plex
`
`docker logs -f plex 
`
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing... 
-------------------------------------
          _     _ _
         | |___| (_) ___
         | / __| | |/ _ \ 
         | \__ \ | | (_) |
         |_|___/ |_|\___/
               |_|
Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/index.php/donations/
-------------------------------------
GID/UID
-------------------------------------
User uid:    501
User gid:    501
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-dbus: executing... 
[cont-init.d] 30-dbus: exited 0.
[cont-init.d] 40-chown-files: executing... 
[cont-init.d] 40-chown-files: exited 0.
[cont-init.d] 50-plex-update: executing... 
#####################################################
#   Login via the webui at http://<ip>:32400/web    #
#   and restart the docker, because there was no    #
#   preference file found, possibly first startup.  #
#####################################################
[cont-init.d] 50-plex-update: exited 0.
[cont-init.d] done.
[services.d] starting services
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise avahi: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise plex: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
[services.d] done.
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise avahi: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise plex: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise (child): fatal: unable to exec run: Permission denied
s6-supervise dbus: warning: unable to spawn ./run - waiting 10 seconds
```

and on and on...

I'm running 
```
# docker --version
Docker version 1.10.3, build e03ddb8/1.10.3
```

On Fedora 24

**Comment by redlegoman** [comment]
Stupid. Just noticed my errors in startup line - missed to inside directories off each -v line.

**Comment by redlegoman** [comment]
Changed the create to :
```
docker create \
--name=plex \
--net=host \
-e VERSION=latest \
-e PUID=0 -e PGID=0 \
-e TZ=Europe/London \
-v /data/data1/SHARED/plex1/config:/config \
-v /data/data1/SHARED/plex1/data/tvshows:/data/tvshows \
-v /data/data1/SHARED/plex1/data/movies:/data/movies \
-v /data/data1/SHARED/plex1/transcode:/transcode \
linuxserver/plex
```
But I am still getting the "permission denied" errors and no running plex.

**Comment by redlegoman** [comment]
if I run a bash shell I can start plex by running 
```
# exec s6-setuidgid abc /usr/sbin/start_pms
6 3000 /config/Library/Application Support
8192
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/Fanart-TV.bundle.
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/HTbackdrops.bundle.
Error starting framework core for /usr/lib/plexmediaserver/Resources/Plug-ins-1bef33a/LastFM.bundle.

```
but not by running:
```
#:/var/run/s6/services/plex# ./run
bash: ./run: Permission denied
```

**Comment by sparklyballs** [comment]
this appears to be something specific to fedora at this stage of investigation.

**Comment by acathrow** [comment]
Why is this issue closed?
If Fedora (or CentOS/RHEL with Red Hat supplied docker) isn't supported, which IMHO would be  a mistake since the issue seems to be within the s6-overlay project's incorrect assumptions, then the website, README, etc should clearly state that. Otherwise the issue should remain open. 

Otherwise surely the issue should remain open -especially since there is no work around in here?

There's more detail, including a work around here
https://github.com/just-containers/s6-overlay/issues/158
and Red Hat commentary on the issue
https://bugzilla.redhat.com/show_bug.cgi?id=1375661

**Comment by sparklyballs** [comment]
Because the issue is with fedora, it's not an s6 issue either.

i've read both of those posts before. 

first line of the fedora page on docker 

"Docker is supported on Fedora version 22, 23, and 24."

https://docs.docker.com/engine/installation/linux/fedora/

25 isn't supported by docker

**Comment by acathrow** [comment]
When you say Docker isn't supported on Fedora 25 that's not strictly correct.
You are talking about the binaries supplied by Docker Inc.
Docker is a project. There are distributions of Docker provide by different organizations much like there's not one distribution of apache httpd from apache.org

The Linux distributions also provide their binaries of Docker that are optimized for their platforms.
For example, the Docker binaries provided by CentOS, RHEL and Fedora are different that the binaries supplied by Docker Inc. These are fully supported by those distributions and often include maintenance and backports not provided by docker Inc.

It sounds like you are making the statement that you'll only support docker inc. binaries rather than those provided by distributions (eg. centos, fedora, rhel, debian, ubuntu, etc). Personally I'd disagree with that decision, but if that's the official stance then it should be documented.

That said I know that the Red Hat folks are looking at making the noexec on /run optional so this all might be a moot point !

In the mean time I'm working around this with VOLUME ['/run'] 

Thanks for the great work on this docker image..
